
package views.mainOptions;

/**
 *
 * @author Gustavo
 */
public class MainOptions extends javax.swing.JPanel {

    public MainOptions() {
        initComponents();
    }
    
    public void addActionEvents(java.awt.event.ActionListener evt) {
        
        btnWalletManagement.addActionListener(evt);
        btnStats.addActionListener(evt);
        btnSell.addActionListener(evt);
        btnBuy.addActionListener(evt);
        btnBuild.addActionListener(evt);
        btnFixedExpenses.addActionListener(evt);
        btnClient.addActionListener(evt);
        btnProvider.addActionListener(evt);
        btnEmployee.addActionListener(evt);
        btnEnterprise.addActionListener(evt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBtnWallet = new javax.swing.JPanel();
        btnWalletManagement = new javax.swing.JButton();
        panBtnStats = new javax.swing.JPanel();
        btnStats = new javax.swing.JButton();
        panBtnSell = new javax.swing.JPanel();
        btnSell = new javax.swing.JButton();
        panBtnBuy = new javax.swing.JPanel();
        btnBuy = new javax.swing.JButton();
        panBtnBuild = new javax.swing.JPanel();
        btnBuild = new javax.swing.JButton();
        panBtnClient = new javax.swing.JPanel();
        btnClient = new javax.swing.JButton();
        panBtnEmployee = new javax.swing.JPanel();
        btnEmployee = new javax.swing.JButton();
        panBtnFixedExpenses = new javax.swing.JPanel();
        btnFixedExpenses = new javax.swing.JButton();
        panBtnProvider = new javax.swing.JPanel();
        btnProvider = new javax.swing.JButton();
        panBtnEnterprise = new javax.swing.JPanel();
        btnEnterprise = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 245, 249));
        setMaximumSize(new java.awt.Dimension(748, 654));
        setMinimumSize(new java.awt.Dimension(748, 654));
        setPreferredSize(new java.awt.Dimension(748, 654));

        panBtnWallet.setBackground(new java.awt.Color(255, 245, 249));
        panBtnWallet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnWalletManagement.setBackground(new java.awt.Color(255, 245, 249));
        btnWalletManagement.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnWalletManagement.setForeground(new java.awt.Color(0, 0, 0));
        btnWalletManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/walletIcon.png"))); // NOI18N
        btnWalletManagement.setText("<html><b><p align = 'center'><FONT SIZE=4>Billetera</font></p></b><br><p align = 'justify'>Visualiza los movimientos de tus recursos y adminístralos de forma inteligente.</p></html>");
        btnWalletManagement.setToolTipText("");
        btnWalletManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnWalletManagement.setBorderPainted(false);
        btnWalletManagement.setContentAreaFilled(false);
        btnWalletManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWalletManagement.setFocusPainted(false);
        btnWalletManagement.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnWalletManagement.setIconTextGap(30);
        btnWalletManagement.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnWalletManagement.setOpaque(true);
        btnWalletManagement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnWalletManagementMouseMoved(evt);
            }
        });
        btnWalletManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWalletManagementMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnWalletLayout = new javax.swing.GroupLayout(panBtnWallet);
        panBtnWallet.setLayout(panBtnWalletLayout);
        panBtnWalletLayout.setHorizontalGroup(
            panBtnWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnWalletLayout.createSequentialGroup()
                .addComponent(btnWalletManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panBtnWalletLayout.setVerticalGroup(
            panBtnWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnWalletManagement)
        );

        panBtnStats.setBackground(new java.awt.Color(255, 245, 249));
        panBtnStats.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnStats.setBackground(new java.awt.Color(255, 245, 249));
        btnStats.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnStats.setForeground(new java.awt.Color(0, 0, 0));
        btnStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/statsIcon.png"))); // NOI18N
        btnStats.setText("<html><b><p align = 'center'><FONT SIZE=4>Estadísticas</font></p></b><br><p align = 'justify'>Chequea como van tus compras y ventas para apoyar tu toma de decisiones.</p></html>");
        btnStats.setToolTipText("");
        btnStats.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnStats.setBorderPainted(false);
        btnStats.setContentAreaFilled(false);
        btnStats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStats.setFocusPainted(false);
        btnStats.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnStats.setIconTextGap(30);
        btnStats.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnStats.setOpaque(true);
        btnStats.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnStatsMouseMoved(evt);
            }
        });
        btnStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnStatsLayout = new javax.swing.GroupLayout(panBtnStats);
        panBtnStats.setLayout(panBtnStatsLayout);
        panBtnStatsLayout.setHorizontalGroup(
            panBtnStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panBtnStatsLayout.setVerticalGroup(
            panBtnStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnStatsLayout.createSequentialGroup()
                .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panBtnSell.setBackground(new java.awt.Color(255, 245, 249));
        panBtnSell.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnSell.setBackground(new java.awt.Color(255, 245, 249));
        btnSell.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSell.setForeground(new java.awt.Color(0, 0, 0));
        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/sellIcon.png"))); // NOI18N
        btnSell.setText("<html><b><p align = 'center'><FONT SIZE=4>Ventas</font></p></b><br><p align = 'justify'>Realiza las ventas de tus productos a todos tus clientes de forma muy fácil y rápida.</p></html>");
        btnSell.setToolTipText("");
        btnSell.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnSell.setBorderPainted(false);
        btnSell.setContentAreaFilled(false);
        btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSell.setFocusPainted(false);
        btnSell.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSell.setIconTextGap(30);
        btnSell.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnSell.setOpaque(true);
        btnSell.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSellMouseMoved(evt);
            }
        });
        btnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSellMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnSellLayout = new javax.swing.GroupLayout(panBtnSell);
        panBtnSell.setLayout(panBtnSellLayout);
        panBtnSellLayout.setHorizontalGroup(
            panBtnSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnSellLayout.setVerticalGroup(
            panBtnSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnSellLayout.createSequentialGroup()
                .addComponent(btnSell)
                .addGap(1, 1, 1))
        );

        panBtnBuy.setBackground(new java.awt.Color(255, 245, 249));
        panBtnBuy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnBuy.setBackground(new java.awt.Color(255, 245, 249));
        btnBuy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(0, 0, 0));
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/buyIcon.png"))); // NOI18N
        btnBuy.setText("<html><b><p align = 'center'><FONT SIZE=4>Compras</font></p></b><br><p align = 'justify'>Gestiona la compra de tus insumos para la elaboración de los productos a vender.</p></html>");
        btnBuy.setToolTipText("");
        btnBuy.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        btnBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuy.setFocusPainted(false);
        btnBuy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuy.setIconTextGap(30);
        btnBuy.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnBuy.setOpaque(true);
        btnBuy.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuyMouseMoved(evt);
            }
        });
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnBuyLayout = new javax.swing.GroupLayout(panBtnBuy);
        panBtnBuy.setLayout(panBtnBuyLayout);
        panBtnBuyLayout.setHorizontalGroup(
            panBtnBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnBuyLayout.setVerticalGroup(
            panBtnBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnBuyLayout.createSequentialGroup()
                .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panBtnBuild.setBackground(new java.awt.Color(255, 245, 249));
        panBtnBuild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnBuild.setBackground(new java.awt.Color(255, 245, 249));
        btnBuild.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuild.setForeground(new java.awt.Color(0, 0, 0));
        btnBuild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/buildIcon.png"))); // NOI18N
        btnBuild.setText("<html><b><p align = 'center'><FONT SIZE=4>Fabricar</font></p></b><br><p align = 'justify'>Registra los productos a vender mediante un formulario práctico y simple.</p></html>");
        btnBuild.setToolTipText("");
        btnBuild.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnBuild.setBorderPainted(false);
        btnBuild.setContentAreaFilled(false);
        btnBuild.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuild.setFocusPainted(false);
        btnBuild.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuild.setIconTextGap(30);
        btnBuild.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnBuild.setOpaque(true);
        btnBuild.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuildMouseMoved(evt);
            }
        });
        btnBuild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuildMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnBuildLayout = new javax.swing.GroupLayout(panBtnBuild);
        panBtnBuild.setLayout(panBtnBuildLayout);
        panBtnBuildLayout.setHorizontalGroup(
            panBtnBuildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuild, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnBuildLayout.setVerticalGroup(
            panBtnBuildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnBuildLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnBuild))
        );

        panBtnClient.setBackground(new java.awt.Color(255, 245, 249));
        panBtnClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnClient.setBackground(new java.awt.Color(255, 245, 249));
        btnClient.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClient.setForeground(new java.awt.Color(0, 0, 0));
        btnClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/clientIcon.png"))); // NOI18N
        btnClient.setText("<html><b><p align = 'center'><FONT SIZE=4>Clientes</font></p></b><br><p align = 'justify'>Lleva un directorio de todos tus clientes, de forma que podrás enlazar las compras a ellos fácilmente.</p></html>");
        btnClient.setToolTipText("");
        btnClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnClient.setBorderPainted(false);
        btnClient.setContentAreaFilled(false);
        btnClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClient.setFocusPainted(false);
        btnClient.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnClient.setIconTextGap(30);
        btnClient.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnClient.setOpaque(true);
        btnClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClientMouseMoved(evt);
            }
        });
        btnClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnClientLayout = new javax.swing.GroupLayout(panBtnClient);
        panBtnClient.setLayout(panBtnClientLayout);
        panBtnClientLayout.setHorizontalGroup(
            panBtnClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnClientLayout.setVerticalGroup(
            panBtnClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClient)
        );

        panBtnEmployee.setBackground(new java.awt.Color(255, 245, 249));
        panBtnEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnEmployee.setBackground(new java.awt.Color(255, 245, 249));
        btnEmployee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/employeeIcon.png"))); // NOI18N
        btnEmployee.setText("<html><b><p align = 'center'><FONT SIZE=4>Empleados</font></p></b><br><p align = 'justify'>Gestion la información de los empleados de tu empresa y los usuarios que les corresponde.</p></html>");
        btnEmployee.setToolTipText("");
        btnEmployee.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnEmployee.setBorderPainted(false);
        btnEmployee.setContentAreaFilled(false);
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.setFocusPainted(false);
        btnEmployee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnEmployee.setIconTextGap(30);
        btnEmployee.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnEmployee.setOpaque(true);
        btnEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseMoved(evt);
            }
        });
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnEmployeeLayout = new javax.swing.GroupLayout(panBtnEmployee);
        panBtnEmployee.setLayout(panBtnEmployeeLayout);
        panBtnEmployeeLayout.setHorizontalGroup(
            panBtnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnEmployeeLayout.setVerticalGroup(
            panBtnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panBtnFixedExpenses.setBackground(new java.awt.Color(255, 245, 249));
        panBtnFixedExpenses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnFixedExpenses.setBackground(new java.awt.Color(255, 245, 249));
        btnFixedExpenses.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFixedExpenses.setForeground(new java.awt.Color(0, 0, 0));
        btnFixedExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/fixedExpenseIcon.png"))); // NOI18N
        btnFixedExpenses.setText("<html><b><p align = 'center'><FONT SIZE=4>Gastos Fijos</font></p></b><br><p align = 'justify'>Mantén un control de todos los gastos fijos que genera tu empresa durante todo el mes.</p></html>");
        btnFixedExpenses.setToolTipText("");
        btnFixedExpenses.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnFixedExpenses.setBorderPainted(false);
        btnFixedExpenses.setContentAreaFilled(false);
        btnFixedExpenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFixedExpenses.setFocusPainted(false);
        btnFixedExpenses.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnFixedExpenses.setIconTextGap(30);
        btnFixedExpenses.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnFixedExpenses.setOpaque(true);
        btnFixedExpenses.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnFixedExpensesMouseMoved(evt);
            }
        });
        btnFixedExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFixedExpensesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnFixedExpensesLayout = new javax.swing.GroupLayout(panBtnFixedExpenses);
        panBtnFixedExpenses.setLayout(panBtnFixedExpensesLayout);
        panBtnFixedExpensesLayout.setHorizontalGroup(
            panBtnFixedExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFixedExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnFixedExpensesLayout.setVerticalGroup(
            panBtnFixedExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFixedExpenses, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panBtnProvider.setBackground(new java.awt.Color(255, 245, 249));
        panBtnProvider.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnProvider.setBackground(new java.awt.Color(255, 245, 249));
        btnProvider.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnProvider.setForeground(new java.awt.Color(0, 0, 0));
        btnProvider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/providerIcon.png"))); // NOI18N
        btnProvider.setText("<html><b><p align = 'center'><FONT SIZE=4>Proveedores</font></p></b><br><p align = 'justify'>Siempre es bueno y muy recomendable tener un listado de tus proveedores de confianza.</p></html>");
        btnProvider.setToolTipText("");
        btnProvider.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnProvider.setBorderPainted(false);
        btnProvider.setContentAreaFilled(false);
        btnProvider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProvider.setFocusPainted(false);
        btnProvider.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnProvider.setIconTextGap(30);
        btnProvider.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnProvider.setOpaque(true);
        btnProvider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnProviderMouseMoved(evt);
            }
        });
        btnProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProviderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnProviderLayout = new javax.swing.GroupLayout(panBtnProvider);
        panBtnProvider.setLayout(panBtnProviderLayout);
        panBtnProviderLayout.setHorizontalGroup(
            panBtnProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnProviderLayout.setVerticalGroup(
            panBtnProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnProviderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panBtnEnterprise.setBackground(new java.awt.Color(255, 245, 249));
        panBtnEnterprise.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnEnterprise.setBackground(new java.awt.Color(255, 245, 249));
        btnEnterprise.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEnterprise.setForeground(new java.awt.Color(0, 0, 0));
        btnEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/enterpriseIcon.png"))); // NOI18N
        btnEnterprise.setText("<html><b><p align = 'center'><FONT SIZE=4>Empresa</font></p></b><br><p align = 'justify'>Visualiza la información de la empresa y de ser necesario, realiza los ajustes que creas correspondientes.</p></html>");
        btnEnterprise.setToolTipText("");
        btnEnterprise.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnEnterprise.setBorderPainted(false);
        btnEnterprise.setContentAreaFilled(false);
        btnEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnterprise.setFocusPainted(false);
        btnEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnEnterprise.setIconTextGap(30);
        btnEnterprise.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnEnterprise.setOpaque(true);
        btnEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEnterpriseMouseMoved(evt);
            }
        });
        btnEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterpriseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnEnterpriseLayout = new javax.swing.GroupLayout(panBtnEnterprise);
        panBtnEnterprise.setLayout(panBtnEnterpriseLayout);
        panBtnEnterpriseLayout.setHorizontalGroup(
            panBtnEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnEnterpriseLayout.setVerticalGroup(
            panBtnEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnEnterpriseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panBtnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panBtnBuild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnWallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnFixedExpenses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnProvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnWallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBtnBuild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnFixedExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBtnProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panBtnClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWalletManagementMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWalletManagementMouseMoved
        panBtnWallet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnWalletManagementMouseMoved

    private void btnWalletManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWalletManagementMouseExited
        panBtnWallet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnWalletManagementMouseExited

    private void btnStatsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseMoved
        panBtnStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnStatsMouseMoved

    private void btnStatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseExited
        panBtnStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnStatsMouseExited

    private void btnSellMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseMoved
        panBtnSell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnSellMouseMoved

    private void btnSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseExited
        panBtnSell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnSellMouseExited

    private void btnBuyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseMoved
        panBtnBuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnBuyMouseMoved

    private void btnBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseExited
        panBtnBuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnBuyMouseExited

    private void btnBuildMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuildMouseMoved
        panBtnBuild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnBuildMouseMoved

    private void btnBuildMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuildMouseExited
        panBtnBuild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnBuildMouseExited

    private void btnClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseMoved
        panBtnClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnClientMouseMoved

    private void btnClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseExited
        panBtnClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnClientMouseExited

    private void btnEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseMoved
        panBtnEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnEmployeeMouseMoved

    private void btnEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseExited
        panBtnEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnEmployeeMouseExited

    private void btnFixedExpensesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFixedExpensesMouseMoved
        panBtnFixedExpenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnFixedExpensesMouseMoved

    private void btnFixedExpensesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFixedExpensesMouseExited
        panBtnFixedExpenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnFixedExpensesMouseExited

    private void btnProviderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProviderMouseMoved
        panBtnProvider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnProviderMouseMoved

    private void btnProviderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProviderMouseExited
        panBtnProvider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnProviderMouseExited

    private void btnEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterpriseMouseMoved
        panBtnEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnEnterpriseMouseMoved

    private void btnEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterpriseMouseExited
        panBtnEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnEnterpriseMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuild;
    public javax.swing.JButton btnBuy;
    public javax.swing.JButton btnClient;
    public javax.swing.JButton btnEmployee;
    public javax.swing.JButton btnEnterprise;
    public javax.swing.JButton btnFixedExpenses;
    public javax.swing.JButton btnProvider;
    public javax.swing.JButton btnSell;
    public javax.swing.JButton btnStats;
    public javax.swing.JButton btnWalletManagement;
    private javax.swing.JPanel panBtnBuild;
    private javax.swing.JPanel panBtnBuy;
    private javax.swing.JPanel panBtnClient;
    private javax.swing.JPanel panBtnEmployee;
    private javax.swing.JPanel panBtnEnterprise;
    private javax.swing.JPanel panBtnFixedExpenses;
    private javax.swing.JPanel panBtnProvider;
    private javax.swing.JPanel panBtnSell;
    private javax.swing.JPanel panBtnStats;
    private javax.swing.JPanel panBtnWallet;
    // End of variables declaration//GEN-END:variables
}
