
package views.mainOptions;

/**
 *
 * @author Gustavo
 */
public class MainOptions extends javax.swing.JPanel {

    public MainOptions() {
        initComponents();
    }
    
    public void addActionEvents(java.awt.event.ActionListener evt) {
        
        btnWalletManagement.addActionListener(evt);
        btnStats.addActionListener(evt);
        btnSell.addActionListener(evt);
        btnBuy.addActionListener(evt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBtnWallet = new javax.swing.JPanel();
        btnWalletManagement = new javax.swing.JButton();
        panBtnStats = new javax.swing.JPanel();
        btnStats = new javax.swing.JButton();
        panBtnSell = new javax.swing.JPanel();
        btnSell = new javax.swing.JButton();
        panBtnBuy = new javax.swing.JPanel();
        btnBuy = new javax.swing.JButton();
        panBtnBuild = new javax.swing.JPanel();
        btnBuild = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 245, 249));
        setMaximumSize(new java.awt.Dimension(748, 654));
        setMinimumSize(new java.awt.Dimension(748, 654));
        setPreferredSize(new java.awt.Dimension(748, 654));

        panBtnWallet.setBackground(new java.awt.Color(255, 245, 249));
        panBtnWallet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnWalletManagement.setBackground(new java.awt.Color(255, 245, 249));
        btnWalletManagement.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnWalletManagement.setForeground(new java.awt.Color(0, 0, 0));
        btnWalletManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/walletIcon.png"))); // NOI18N
        btnWalletManagement.setText("<html><b><p align = 'center'><FONT SIZE=4>Billetera</font></p></b><br><p align = 'justify'>Visualiza los movimientos de tus recursos y adminístralos de forma inteligente.</p></html>");
        btnWalletManagement.setToolTipText("");
        btnWalletManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnWalletManagement.setBorderPainted(false);
        btnWalletManagement.setContentAreaFilled(false);
        btnWalletManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWalletManagement.setFocusPainted(false);
        btnWalletManagement.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnWalletManagement.setIconTextGap(30);
        btnWalletManagement.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnWalletManagement.setOpaque(true);
        btnWalletManagement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnWalletManagementMouseMoved(evt);
            }
        });
        btnWalletManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWalletManagementMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnWalletLayout = new javax.swing.GroupLayout(panBtnWallet);
        panBtnWallet.setLayout(panBtnWalletLayout);
        panBtnWalletLayout.setHorizontalGroup(
            panBtnWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnWalletLayout.createSequentialGroup()
                .addComponent(btnWalletManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panBtnWalletLayout.setVerticalGroup(
            panBtnWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnWalletManagement)
        );

        panBtnStats.setBackground(new java.awt.Color(255, 245, 249));
        panBtnStats.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnStats.setBackground(new java.awt.Color(255, 245, 249));
        btnStats.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnStats.setForeground(new java.awt.Color(0, 0, 0));
        btnStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/statsIcon.png"))); // NOI18N
        btnStats.setText("<html><b><p align = 'center'><FONT SIZE=4>Estadísticas</font></p></b><br><p align = 'justify'>Chequea como van tus compras y ventas para apoyar tu toma de decisiones.</p></html>");
        btnStats.setToolTipText("");
        btnStats.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnStats.setBorderPainted(false);
        btnStats.setContentAreaFilled(false);
        btnStats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStats.setFocusPainted(false);
        btnStats.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnStats.setIconTextGap(30);
        btnStats.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnStats.setOpaque(true);
        btnStats.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnStatsMouseMoved(evt);
            }
        });
        btnStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnStatsLayout = new javax.swing.GroupLayout(panBtnStats);
        panBtnStats.setLayout(panBtnStatsLayout);
        panBtnStatsLayout.setHorizontalGroup(
            panBtnStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panBtnStatsLayout.setVerticalGroup(
            panBtnStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnStatsLayout.createSequentialGroup()
                .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panBtnSell.setBackground(new java.awt.Color(255, 245, 249));
        panBtnSell.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnSell.setBackground(new java.awt.Color(255, 245, 249));
        btnSell.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSell.setForeground(new java.awt.Color(0, 0, 0));
        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/sellIcon.png"))); // NOI18N
        btnSell.setText("<html><b><p align = 'center'><FONT SIZE=4>Ventas</font></p></b><br><p align = 'justify'>Realiza las ventas de tus productos a todos tus clientes de forma muy fácil y rápida.</p></html>");
        btnSell.setToolTipText("");
        btnSell.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnSell.setBorderPainted(false);
        btnSell.setContentAreaFilled(false);
        btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSell.setFocusPainted(false);
        btnSell.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSell.setIconTextGap(30);
        btnSell.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnSell.setOpaque(true);
        btnSell.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSellMouseMoved(evt);
            }
        });
        btnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSellMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnSellLayout = new javax.swing.GroupLayout(panBtnSell);
        panBtnSell.setLayout(panBtnSellLayout);
        panBtnSellLayout.setHorizontalGroup(
            panBtnSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnSellLayout.setVerticalGroup(
            panBtnSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnSellLayout.createSequentialGroup()
                .addComponent(btnSell)
                .addGap(1, 1, 1))
        );

        panBtnBuy.setBackground(new java.awt.Color(255, 245, 249));
        panBtnBuy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnBuy.setBackground(new java.awt.Color(255, 245, 249));
        btnBuy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(0, 0, 0));
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/buyIcon.png"))); // NOI18N
        btnBuy.setText("<html><b><p align = 'center'><FONT SIZE=4>Compras</font></p></b><br><p align = 'justify'>Gestiona la compra de tus insumos para la elaboración de los productos a vender.</p></html>");
        btnBuy.setToolTipText("");
        btnBuy.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        btnBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuy.setFocusPainted(false);
        btnBuy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuy.setIconTextGap(30);
        btnBuy.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnBuy.setOpaque(true);
        btnBuy.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuyMouseMoved(evt);
            }
        });
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnBuyLayout = new javax.swing.GroupLayout(panBtnBuy);
        panBtnBuy.setLayout(panBtnBuyLayout);
        panBtnBuyLayout.setHorizontalGroup(
            panBtnBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnBuyLayout.setVerticalGroup(
            panBtnBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBtnBuyLayout.createSequentialGroup()
                .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panBtnBuild.setBackground(new java.awt.Color(255, 245, 249));
        panBtnBuild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnBuild.setBackground(new java.awt.Color(255, 245, 249));
        btnBuild.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuild.setForeground(new java.awt.Color(0, 0, 0));
        btnBuild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/buildIcon.png"))); // NOI18N
        btnBuild.setText("<html><b><p align = 'center'><FONT SIZE=4>Fabricar</font></p></b><br><p align = 'justify'>Registra los productos a vender mediante un formulario práctico y simple.</p></html>");
        btnBuild.setToolTipText("");
        btnBuild.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnBuild.setBorderPainted(false);
        btnBuild.setContentAreaFilled(false);
        btnBuild.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuild.setFocusPainted(false);
        btnBuild.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuild.setIconTextGap(30);
        btnBuild.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnBuild.setOpaque(true);
        btnBuild.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuildMouseMoved(evt);
            }
        });
        btnBuild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuildMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnBuildLayout = new javax.swing.GroupLayout(panBtnBuild);
        panBtnBuild.setLayout(panBtnBuildLayout);
        panBtnBuildLayout.setHorizontalGroup(
            panBtnBuildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuild, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panBtnBuildLayout.setVerticalGroup(
            panBtnBuildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnBuildLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panBtnBuild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnWallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnWallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBtnBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panBtnBuild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(297, 297, 297))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWalletManagementMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWalletManagementMouseMoved
        panBtnWallet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnWalletManagementMouseMoved

    private void btnWalletManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWalletManagementMouseExited
        panBtnWallet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnWalletManagementMouseExited

    private void btnStatsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseMoved
        panBtnStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnStatsMouseMoved

    private void btnStatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseExited
        panBtnStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnStatsMouseExited

    private void btnSellMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseMoved
        panBtnSell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnSellMouseMoved

    private void btnSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseExited
        panBtnSell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnSellMouseExited

    private void btnBuyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseMoved
        panBtnBuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnBuyMouseMoved

    private void btnBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseExited
        panBtnBuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnBuyMouseExited

    private void btnBuildMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuildMouseMoved
        panBtnBuild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnBuildMouseMoved

    private void btnBuildMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuildMouseExited
        panBtnBuild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnBuildMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuild;
    public javax.swing.JButton btnBuy;
    public javax.swing.JButton btnSell;
    public javax.swing.JButton btnStats;
    public javax.swing.JButton btnWalletManagement;
    private javax.swing.JPanel panBtnBuild;
    private javax.swing.JPanel panBtnBuy;
    private javax.swing.JPanel panBtnSell;
    private javax.swing.JPanel panBtnStats;
    private javax.swing.JPanel panBtnWallet;
    // End of variables declaration//GEN-END:variables
}
