
package views.mainOptions.enterprise;

import lib.SupportFunctions;

/**
 *
 * @author Gustavo
 */
public class EnterpriseManagement extends javax.swing.JPanel {

    private SupportFunctions support = new SupportFunctions();
    
    /**
     * Creates new form userProfile
     * @param photo
     */
    public EnterpriseManagement() {
           
        initComponents();
        
             
    }
    
        /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor 
     * profundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addActionEvents(java.awt.event.ActionListener evt){
             
        btnClearData.addActionListener(evt);
        btnUpdateData.addActionListener(evt);
        btnClose.addActionListener(evt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePhoto = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblUserSurname = new javax.swing.JLabel();
        txtUserSurname = new javax.swing.JTextField();
        lblUserPhone = new javax.swing.JLabel();
        txtUserPhone = new javax.swing.JTextField();
        lblUserDirection = new javax.swing.JLabel();
        txtUserDirection = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        btnClearData = new javax.swing.JButton();
        btnUpdateData = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 245, 249));
        setMaximumSize(new java.awt.Dimension(748, 654));
        setMinimumSize(new java.awt.Dimension(748, 654));
        setPreferredSize(new java.awt.Dimension(748, 654));

        lblProfilePhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 144, 158)));

        lblDNI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDNI.setText("Documento de Identificación: ");

        txtDNI.setBackground(new java.awt.Color(255, 245, 249));
        txtDNI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDNI.setText("Ingresa un documento de identificación");
        txtDNI.setToolTipText("");
        txtDNI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 144, 158)));
        txtDNI.setSelectionColor(new java.awt.Color(0, 144, 158));
        txtDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDNIMouseClicked(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserName.setText("Nombre:");

        txtUserName.setBackground(new java.awt.Color(255, 245, 249));
        txtUserName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserName.setText("Ingresa tu nombre");
        txtUserName.setToolTipText("");
        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 144, 158)));
        txtUserName.setSelectionColor(new java.awt.Color(0, 144, 158));
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });

        lblUserSurname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserSurname.setText("Descripción:");

        txtUserSurname.setBackground(new java.awt.Color(255, 245, 249));
        txtUserSurname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserSurname.setText("Ingresa tu apellido");
        txtUserSurname.setToolTipText("");
        txtUserSurname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 144, 158)));
        txtUserSurname.setSelectionColor(new java.awt.Color(0, 144, 158));
        txtUserSurname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserSurnameMouseClicked(evt);
            }
        });

        lblUserPhone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserPhone.setText("Teléfono: ");

        txtUserPhone.setBackground(new java.awt.Color(255, 245, 249));
        txtUserPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserPhone.setText("Ingresa tu número telefónico");
        txtUserPhone.setToolTipText("");
        txtUserPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 144, 158)));
        txtUserPhone.setSelectionColor(new java.awt.Color(0, 144, 158));
        txtUserPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserPhoneMouseClicked(evt);
            }
        });
        txtUserPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserPhoneKeyTyped(evt);
            }
        });

        lblUserDirection.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserDirection.setText("Dirección: ");

        txtUserDirection.setBackground(new java.awt.Color(255, 245, 249));
        txtUserDirection.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserDirection.setText("Ingresa tu dirección");
        txtUserDirection.setToolTipText("");
        txtUserDirection.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 144, 158)));
        txtUserDirection.setSelectionColor(new java.awt.Color(0, 144, 158));
        txtUserDirection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserDirectionMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos de la Empresa");

        lblUserEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserEmail.setText("Correo electrónico: ");

        txtUserEmail.setBackground(new java.awt.Color(255, 245, 249));
        txtUserEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserEmail.setText("Ingresa tu correo electrónico");
        txtUserEmail.setToolTipText("");
        txtUserEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 144, 158)));
        txtUserEmail.setSelectionColor(new java.awt.Color(0, 144, 158));
        txtUserEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserEmailMouseClicked(evt);
            }
        });

        btnClearData.setBackground(new java.awt.Color(254, 220, 234));
        btnClearData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearData.setForeground(new java.awt.Color(0, 0, 0));
        btnClearData.setText("Limpiar");
        btnClearData.setToolTipText("Limpiar datos");
        btnClearData.setBorder(null);
        btnClearData.setBorderPainted(false);
        btnClearData.setContentAreaFilled(false);
        btnClearData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearData.setFocusPainted(false);
        btnClearData.setOpaque(true);
        btnClearData.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearDataMouseMoved(evt);
            }
        });
        btnClearData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearDataMouseExited(evt);
            }
        });

        btnUpdateData.setBackground(new java.awt.Color(254, 220, 234));
        btnUpdateData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateData.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateData.setText("Actualizar");
        btnUpdateData.setToolTipText("Actualizar datos");
        btnUpdateData.setBorder(null);
        btnUpdateData.setBorderPainted(false);
        btnUpdateData.setContentAreaFilled(false);
        btnUpdateData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateData.setFocusPainted(false);
        btnUpdateData.setOpaque(true);
        btnUpdateData.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUpdateDataMouseMoved(evt);
            }
        });
        btnUpdateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateDataMouseExited(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(254, 220, 234));
        btnClose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 0, 0));
        btnClose.setText("Cerrar");
        btnClose.setToolTipText("Cerrar");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.setOpaque(true);
        btnClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCloseMouseMoved(evt);
            }
        });
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUserPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDNI)
                                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblUserDirection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUserSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserSurname)
                                    .addComponent(txtUserDirection, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClearData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearData, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIMouseClicked
        if(txtDNI.getText().equals("Ingresa tu documento de identificación"))
        txtDNI.setText("");
    }//GEN-LAST:event_txtDNIMouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        if(txtUserName.getText().equals("Ingresa tu nombre"))
        txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtUserPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserPhoneMouseClicked
        if(txtUserPhone.getText().equals("Ingresa tu número telefónico"))
        txtUserPhone.setText("");
    }//GEN-LAST:event_txtUserPhoneMouseClicked

    private void txtUserPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserPhoneKeyTyped
        support.integerPositiveKeyTyped(evt);
    }//GEN-LAST:event_txtUserPhoneKeyTyped

    private void txtUserDirectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserDirectionMouseClicked
        if(txtUserDirection.getText().equals("Ingresa tu dirección"))
        txtUserDirection.setText("");
    }//GEN-LAST:event_txtUserDirectionMouseClicked

    private void txtUserEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserEmailMouseClicked
        if(txtUserEmail.getText().equals("Ingresa tu correo electrónico"))
        txtUserEmail.setText("");
    }//GEN-LAST:event_txtUserEmailMouseClicked

    private void btnClearDataMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearDataMouseMoved
        btnClearData.setForeground(new java.awt.Color(255,230,240));
        btnClearData.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnClearDataMouseMoved

    private void btnClearDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearDataMouseExited
        btnClearData.setForeground(new java.awt.Color(0, 0, 0));
        btnClearData.setBackground(new java.awt.Color(254,220,234));
    }//GEN-LAST:event_btnClearDataMouseExited

    private void btnUpdateDataMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateDataMouseMoved
        btnUpdateData.setForeground(new java.awt.Color(255,230,240));
        btnUpdateData.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnUpdateDataMouseMoved

    private void btnUpdateDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateDataMouseExited
        btnUpdateData.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateData.setBackground(new java.awt.Color(254,220,234));
    }//GEN-LAST:event_btnUpdateDataMouseExited

    private void txtUserSurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserSurnameMouseClicked
        if(txtUserSurname.getText().equals("Ingresa tu apellido"))
        txtUserSurname.setText("");
    }//GEN-LAST:event_txtUserSurnameMouseClicked

    private void btnCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseMoved

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClearData;
    public javax.swing.JButton btnClose;
    public javax.swing.JButton btnUpdateData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblProfilePhoto;
    private javax.swing.JLabel lblUserDirection;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPhone;
    private javax.swing.JLabel lblUserSurname;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtUserDirection;
    public javax.swing.JTextField txtUserEmail;
    public javax.swing.JTextField txtUserName;
    public javax.swing.JTextField txtUserPhone;
    public javax.swing.JTextField txtUserSurname;
    // End of variables declaration//GEN-END:variables
}
