
package views.mainOptions.enterprise;

/**
 *
 * @author Gustavo
 */
public class EnterpriseMenu extends javax.swing.JPanel {

    public EnterpriseMenu() {
        initComponents();
    }
    
    public void addActionEvents(java.awt.event.ActionListener evt) {
        
        btnEnterprise.addActionListener(evt);
        btnEmployee.addActionListener(evt);
        btnStats.addActionListener(evt);
        btnFixedExpenses.addActionListener(evt);
        btnWallet.addActionListener(evt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBtnEnterprise = new javax.swing.JPanel();
        btnEnterprise = new javax.swing.JButton();
        panBtnFixedExpenses = new javax.swing.JPanel();
        btnFixedExpenses = new javax.swing.JButton();
        panBtnStats = new javax.swing.JPanel();
        btnStats = new javax.swing.JButton();
        panBtnWallet = new javax.swing.JPanel();
        btnWallet = new javax.swing.JButton();
        panBtnEmployee = new javax.swing.JPanel();
        btnEmployee = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 245, 249));
        setMaximumSize(new java.awt.Dimension(748, 654));
        setMinimumSize(new java.awt.Dimension(748, 654));
        setPreferredSize(new java.awt.Dimension(748, 654));

        panBtnEnterprise.setBackground(new java.awt.Color(255, 245, 249));
        panBtnEnterprise.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnEnterprise.setBackground(new java.awt.Color(255, 245, 249));
        btnEnterprise.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEnterprise.setForeground(new java.awt.Color(0, 0, 0));
        btnEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/enterpriseIcon.png"))); // NOI18N
        btnEnterprise.setText("<html><b><p align = 'Justify'><FONT SIZE=3>Empresa</font></p></b><p align = 'justify'>Gestiona la información principal de la empresa.</p></html>");
        btnEnterprise.setToolTipText("");
        btnEnterprise.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnEnterprise.setBorderPainted(false);
        btnEnterprise.setContentAreaFilled(false);
        btnEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnterprise.setFocusPainted(false);
        btnEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEnterprise.setIconTextGap(30);
        btnEnterprise.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnEnterprise.setOpaque(true);
        btnEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEnterpriseMouseMoved(evt);
            }
        });
        btnEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterpriseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnEnterpriseLayout = new javax.swing.GroupLayout(panBtnEnterprise);
        panBtnEnterprise.setLayout(panBtnEnterpriseLayout);
        panBtnEnterpriseLayout.setHorizontalGroup(
            panBtnEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEnterprise)
        );
        panBtnEnterpriseLayout.setVerticalGroup(
            panBtnEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEnterprise)
        );

        panBtnFixedExpenses.setBackground(new java.awt.Color(255, 245, 249));
        panBtnFixedExpenses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnFixedExpenses.setBackground(new java.awt.Color(255, 245, 249));
        btnFixedExpenses.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFixedExpenses.setForeground(new java.awt.Color(0, 0, 0));
        btnFixedExpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/fixedExpenseIcon.png"))); // NOI18N
        btnFixedExpenses.setText("<html><b><p align = 'Justify'><FONT SIZE=3>Gastos Fijos</font></p></b><p align = 'justify'>Administra los gastos fijos que mantiene tu empresa.</p></html>");
        btnFixedExpenses.setToolTipText("");
        btnFixedExpenses.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnFixedExpenses.setBorderPainted(false);
        btnFixedExpenses.setContentAreaFilled(false);
        btnFixedExpenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFixedExpenses.setFocusPainted(false);
        btnFixedExpenses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFixedExpenses.setIconTextGap(30);
        btnFixedExpenses.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnFixedExpenses.setOpaque(true);
        btnFixedExpenses.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnFixedExpensesMouseMoved(evt);
            }
        });
        btnFixedExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFixedExpensesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnFixedExpensesLayout = new javax.swing.GroupLayout(panBtnFixedExpenses);
        panBtnFixedExpenses.setLayout(panBtnFixedExpensesLayout);
        panBtnFixedExpensesLayout.setHorizontalGroup(
            panBtnFixedExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFixedExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        panBtnFixedExpensesLayout.setVerticalGroup(
            panBtnFixedExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFixedExpenses)
        );

        panBtnStats.setBackground(new java.awt.Color(255, 245, 249));
        panBtnStats.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnStats.setBackground(new java.awt.Color(255, 245, 249));
        btnStats.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnStats.setForeground(new java.awt.Color(0, 0, 0));
        btnStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/statsIcon.png"))); // NOI18N
        btnStats.setText("<html><b><p align = 'Justify'><FONT SIZE=3>Estadísticas</font></p></b><p align = 'justify'>Chequea como van tus compras y ventas para apoyar tu toma de decisiones.</p></html>");
        btnStats.setToolTipText("");
        btnStats.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnStats.setBorderPainted(false);
        btnStats.setContentAreaFilled(false);
        btnStats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStats.setFocusPainted(false);
        btnStats.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStats.setIconTextGap(30);
        btnStats.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnStats.setOpaque(true);
        btnStats.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnStatsMouseMoved(evt);
            }
        });
        btnStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnStatsLayout = new javax.swing.GroupLayout(panBtnStats);
        panBtnStats.setLayout(panBtnStatsLayout);
        panBtnStatsLayout.setHorizontalGroup(
            panBtnStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStats, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        panBtnStatsLayout.setVerticalGroup(
            panBtnStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStats)
        );

        panBtnWallet.setBackground(new java.awt.Color(255, 245, 249));
        panBtnWallet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnWallet.setBackground(new java.awt.Color(255, 245, 249));
        btnWallet.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnWallet.setForeground(new java.awt.Color(0, 0, 0));
        btnWallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/walletIcon.png"))); // NOI18N
        btnWallet.setText("<html><b><p align = 'Justify'><FONT SIZE=3>Wallet</font></p></b><p align = 'justify'>Visualiza los movimientos de tus recursos y adminístralos de forma inteligente.</p></html>");
        btnWallet.setToolTipText("");
        btnWallet.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnWallet.setBorderPainted(false);
        btnWallet.setContentAreaFilled(false);
        btnWallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWallet.setFocusPainted(false);
        btnWallet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnWallet.setIconTextGap(30);
        btnWallet.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnWallet.setOpaque(true);
        btnWallet.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnWalletMouseMoved(evt);
            }
        });
        btnWallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWalletMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnWalletLayout = new javax.swing.GroupLayout(panBtnWallet);
        panBtnWallet.setLayout(panBtnWalletLayout);
        panBtnWalletLayout.setHorizontalGroup(
            panBtnWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnWallet, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        panBtnWalletLayout.setVerticalGroup(
            panBtnWalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnWallet)
        );

        panBtnEmployee.setBackground(new java.awt.Color(255, 245, 249));
        panBtnEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 1, true));

        btnEmployee.setBackground(new java.awt.Color(255, 245, 249));
        btnEmployee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/employeeIcon.png"))); // NOI18N
        btnEmployee.setText("<html><b><p align = 'Justify'><FONT SIZE=3>Empleados</font></p></b><p align = 'justify'>Consulta la información de los empleados activos de la empresa</p></html>");
        btnEmployee.setToolTipText("");
        btnEmployee.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 30, 15, 30));
        btnEmployee.setBorderPainted(false);
        btnEmployee.setContentAreaFilled(false);
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.setFocusPainted(false);
        btnEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmployee.setIconTextGap(30);
        btnEmployee.setMargin(new java.awt.Insets(30, 50, 30, 50));
        btnEmployee.setOpaque(true);
        btnEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseMoved(evt);
            }
        });
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBtnEmployeeLayout = new javax.swing.GroupLayout(panBtnEmployee);
        panBtnEmployee.setLayout(panBtnEmployeeLayout);
        panBtnEmployeeLayout.setHorizontalGroup(
            panBtnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployee)
        );
        panBtnEmployeeLayout.setVerticalGroup(
            panBtnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmployee)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBtnEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnFixedExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnWallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBtnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panBtnEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBtnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBtnFixedExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBtnStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBtnWallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterpriseMouseMoved
        panBtnEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnEnterpriseMouseMoved

    private void btnEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterpriseMouseExited
        panBtnEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnEnterpriseMouseExited

    private void btnFixedExpensesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFixedExpensesMouseMoved
        panBtnFixedExpenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnFixedExpensesMouseMoved

    private void btnFixedExpensesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFixedExpensesMouseExited
        panBtnFixedExpenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnFixedExpensesMouseExited

    private void btnStatsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseMoved
        panBtnStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnStatsMouseMoved

    private void btnStatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseExited
        panBtnStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnStatsMouseExited

    private void btnWalletMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWalletMouseMoved
        panBtnWallet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnWalletMouseMoved

    private void btnWalletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWalletMouseExited
        panBtnWallet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnWalletMouseExited

    private void btnEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseMoved
        panBtnEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 48, 111)));
    }//GEN-LAST:event_btnEmployeeMouseMoved

    private void btnEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseExited
        panBtnEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,204,255)));
    }//GEN-LAST:event_btnEmployeeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEmployee;
    public javax.swing.JButton btnEnterprise;
    public javax.swing.JButton btnFixedExpenses;
    public javax.swing.JButton btnStats;
    public javax.swing.JButton btnWallet;
    private javax.swing.JPanel panBtnEmployee;
    private javax.swing.JPanel panBtnEnterprise;
    private javax.swing.JPanel panBtnFixedExpenses;
    private javax.swing.JPanel panBtnStats;
    private javax.swing.JPanel panBtnWallet;
    // End of variables declaration//GEN-END:variables
}
