
package views;

import lib.SupportFunctions;

/**
 *
 * @author Gustavo
 */
public class MainMenu extends javax.swing.JFrame {

    private int xx = 0, xy = 0;
    
    private SupportFunctions support;
    
    public MainMenu() {
        
        initComponents();
                
        support = new SupportFunctions();
        
        support.initialOps(this);
        
    }

    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    public void addActionEvents(java.awt.event.ActionListener evt){
        
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        btnSeeNotification.addActionListener(evt);
        btnSeeProfile.addActionListener(evt);
        btnSignOff.addActionListener(evt);
        
        btnHome.addActionListener(evt);
        btnEnterprise.addActionListener(evt);
        btnProducts.addActionListener(evt);
        btnClients.addActionListener(evt);
        btnReports.addActionListener(evt);
        btnSettings.addActionListener(evt);
                
    }
    
    public void addMouseEvents(java.awt.event.MouseListener evt){
        
        
        
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMainMenu = new javax.swing.JPanel();
        panTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSignOff = new javax.swing.JButton();
        btnSeeProfile = new javax.swing.JButton();
        btnSeeNotification = new javax.swing.JButton();
        panMainPanel = new javax.swing.JPanel();
        panMain = new javax.swing.JPanel();
        panLateralMenu = new javax.swing.JPanel();
        lblCaelestiDevelopment = new javax.swing.JLabel();
        lblLogoOrquidea = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnEnterprise = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnClients = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 249, 249));
        setUndecorated(true);
        setResizable(false);

        panMainMenu.setBackground(new java.awt.Color(255, 245, 249));
        panMainMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 144, 158)));

        panTopBar.setBackground(new java.awt.Color(255, 245, 249));
        panTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panTopBarMouseDragged(evt);
            }
        });
        panTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(255, 245, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/minIcon32.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 245, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/closeIcon32.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        btnSignOff.setBackground(new java.awt.Color(255, 245, 249));
        btnSignOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/signOffIcon32.png"))); // NOI18N
        btnSignOff.setToolTipText("Cerrar Sesión");
        btnSignOff.setBorder(null);
        btnSignOff.setBorderPainted(false);
        btnSignOff.setContentAreaFilled(false);
        btnSignOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignOff.setFocusPainted(false);
        btnSignOff.setOpaque(true);
        btnSignOff.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSignOffMouseMoved(evt);
            }
        });
        btnSignOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignOffMouseExited(evt);
            }
        });

        btnSeeProfile.setBackground(new java.awt.Color(255, 245, 249));
        btnSeeProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/accountProfileIcon32.png"))); // NOI18N
        btnSeeProfile.setToolTipText("Ver Perfil");
        btnSeeProfile.setBorder(null);
        btnSeeProfile.setBorderPainted(false);
        btnSeeProfile.setContentAreaFilled(false);
        btnSeeProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeeProfile.setFocusPainted(false);
        btnSeeProfile.setOpaque(true);
        btnSeeProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeeProfileMouseMoved(evt);
            }
        });
        btnSeeProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeeProfileMouseExited(evt);
            }
        });

        btnSeeNotification.setBackground(new java.awt.Color(255, 245, 249));
        btnSeeNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/notificationOffIcon32.png"))); // NOI18N
        btnSeeNotification.setToolTipText("Ver notificaciones");
        btnSeeNotification.setBorder(null);
        btnSeeNotification.setBorderPainted(false);
        btnSeeNotification.setContentAreaFilled(false);
        btnSeeNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeeNotification.setFocusPainted(false);
        btnSeeNotification.setOpaque(true);
        btnSeeNotification.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeeNotificationMouseMoved(evt);
            }
        });
        btnSeeNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeeNotificationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panTopBarLayout = new javax.swing.GroupLayout(panTopBar);
        panTopBar.setLayout(panTopBarLayout);
        panTopBarLayout.setHorizontalGroup(
            panTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopBarLayout.createSequentialGroup()
                .addContainerGap(556, Short.MAX_VALUE)
                .addComponent(btnSeeNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeeProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(14, 14, 14))
        );
        panTopBarLayout.setVerticalGroup(
            panTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSignOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSeeProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSeeNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panMainPanel.setBackground(new java.awt.Color(255, 245, 249));
        panMainPanel.setLayout(new java.awt.CardLayout());

        panMain.setBackground(new java.awt.Color(255, 245, 249));
        panMain.setPreferredSize(new java.awt.Dimension(748, 654));

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        panMainPanel.add(panMain, "card2");

        panLateralMenu.setBackground(new java.awt.Color(255, 230, 240));
        panLateralMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panLateralMenuMouseDragged(evt);
            }
        });
        panLateralMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panLateralMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panLateralMenuMouseReleased(evt);
            }
        });

        lblCaelestiDevelopment.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaelestiDevelopment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/small/Caelesti Small.png"))); // NOI18N
        lblCaelestiDevelopment.setText("Caelesti Development");

        lblLogoOrquidea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/giant/logoGiant.png"))); // NOI18N

        btnHome.setBackground(new java.awt.Color(255, 230, 240));
        btnHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/homeIcon.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setToolTipText("Inicio");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setIconTextGap(25);
        btnHome.setOpaque(true);
        btnHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHomeMouseMoved(evt);
            }
        });
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        btnEnterprise.setBackground(new java.awt.Color(255, 230, 240));
        btnEnterprise.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnterprise.setForeground(new java.awt.Color(0, 0, 0));
        btnEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/enterpriseIcon.png"))); // NOI18N
        btnEnterprise.setText("Empresa");
        btnEnterprise.setToolTipText("Empresa");
        btnEnterprise.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnEnterprise.setBorderPainted(false);
        btnEnterprise.setContentAreaFilled(false);
        btnEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnterprise.setFocusPainted(false);
        btnEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEnterprise.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEnterprise.setIconTextGap(25);
        btnEnterprise.setOpaque(true);
        btnEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEnterpriseMouseMoved(evt);
            }
        });
        btnEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterpriseMouseExited(evt);
            }
        });

        btnProducts.setBackground(new java.awt.Color(255, 230, 240));
        btnProducts.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(0, 0, 0));
        btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/makeupIcon.png"))); // NOI18N
        btnProducts.setText("Productos");
        btnProducts.setToolTipText("Productos");
        btnProducts.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnProducts.setBorderPainted(false);
        btnProducts.setContentAreaFilled(false);
        btnProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducts.setFocusPainted(false);
        btnProducts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducts.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProducts.setIconTextGap(25);
        btnProducts.setOpaque(true);
        btnProducts.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnProductsMouseMoved(evt);
            }
        });
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductsMouseExited(evt);
            }
        });

        btnClients.setBackground(new java.awt.Color(255, 230, 240));
        btnClients.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClients.setForeground(new java.awt.Color(0, 0, 0));
        btnClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/contactIcon.png"))); // NOI18N
        btnClients.setText("Clientes");
        btnClients.setToolTipText("Clientes");
        btnClients.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnClients.setBorderPainted(false);
        btnClients.setContentAreaFilled(false);
        btnClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClients.setFocusPainted(false);
        btnClients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClients.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClients.setIconTextGap(25);
        btnClients.setOpaque(true);
        btnClients.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClientsMouseMoved(evt);
            }
        });
        btnClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientsMouseExited(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(255, 230, 240));
        btnReports.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(0, 0, 0));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/reportIcon.png"))); // NOI18N
        btnReports.setText("Reportes");
        btnReports.setToolTipText("Reportes");
        btnReports.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnReports.setBorderPainted(false);
        btnReports.setContentAreaFilled(false);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setFocusPainted(false);
        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReports.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReports.setIconTextGap(25);
        btnReports.setOpaque(true);
        btnReports.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReportsMouseMoved(evt);
            }
        });
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(255, 230, 240));
        btnSettings.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(0, 0, 0));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/large/settingsIcon.png"))); // NOI18N
        btnSettings.setText("Configuración");
        btnSettings.setToolTipText("Configuración");
        btnSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnSettings.setBorderPainted(false);
        btnSettings.setContentAreaFilled(false);
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings.setFocusPainted(false);
        btnSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSettings.setIconTextGap(25);
        btnSettings.setOpaque(true);
        btnSettings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSettingsMouseMoved(evt);
            }
        });
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panLateralMenuLayout = new javax.swing.GroupLayout(panLateralMenu);
        panLateralMenu.setLayout(panLateralMenuLayout);
        panLateralMenuLayout.setHorizontalGroup(
            panLateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCaelestiDevelopment, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addGroup(panLateralMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoOrquidea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panLateralMenuLayout.setVerticalGroup(
            panLateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLateralMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblLogoOrquidea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCaelestiDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panMainMenuLayout = new javax.swing.GroupLayout(panMainMenu);
        panMainMenu.setLayout(panMainMenuLayout);
        panMainMenuLayout.setHorizontalGroup(
            panMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainMenuLayout.createSequentialGroup()
                .addComponent(panLateralMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panMainMenuLayout.createSequentialGroup()
                        .addComponent(panMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panMainMenuLayout.setVerticalGroup(
            panMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainMenuLayout.createSequentialGroup()
                .addComponent(panTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panLateralMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMainMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnSignOffMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOffMouseMoved
        btnSignOff.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnSignOffMouseMoved

    private void btnSignOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOffMouseExited
        btnSignOff.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnSignOffMouseExited

    private void btnSeeProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeProfileMouseMoved
        btnSeeProfile.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnSeeProfileMouseMoved

    private void btnSeeProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeProfileMouseExited
        btnSeeProfile.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnSeeProfileMouseExited

    private void btnSeeNotificationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeNotificationMouseMoved
        btnSeeNotification.setBackground(new java.awt.Color(254, 220, 234));
    }//GEN-LAST:event_btnSeeNotificationMouseMoved

    private void btnSeeNotificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeNotificationMouseExited
        btnSeeNotification.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnSeeNotificationMouseExited

    private void panTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panTopBarMouseDragged

    private void panTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panTopBarMousePressed

    private void panTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panTopBarMouseReleased

    private void panLateralMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLateralMenuMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panLateralMenuMouseDragged

    private void panLateralMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLateralMenuMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panLateralMenuMousePressed

    private void panLateralMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLateralMenuMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panLateralMenuMouseReleased

    private void btnHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseMoved
        btnHome.setForeground(new java.awt.Color(255,230,240));
        btnHome.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnHomeMouseMoved

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setBackground(new java.awt.Color(255,230,240));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterpriseMouseMoved
        btnEnterprise.setForeground(new java.awt.Color(255,230,240));
        btnEnterprise.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnEnterpriseMouseMoved

    private void btnEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterpriseMouseExited
        btnEnterprise.setForeground(new java.awt.Color(0, 0, 0));
        btnEnterprise.setBackground(new java.awt.Color(255,230,240));
    }//GEN-LAST:event_btnEnterpriseMouseExited

    private void btnProductsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseMoved
        btnProducts.setForeground(new java.awt.Color(255,230,240));
        btnProducts.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnProductsMouseMoved

    private void btnProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseExited
        btnProducts.setForeground(new java.awt.Color(0, 0, 0));
        btnProducts.setBackground(new java.awt.Color(255,230,240));
    }//GEN-LAST:event_btnProductsMouseExited

    private void btnClientsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseMoved
        btnClients.setForeground(new java.awt.Color(255,230,240));
        btnClients.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnClientsMouseMoved

    private void btnClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseExited
        btnClients.setForeground(new java.awt.Color(0, 0, 0));
        btnClients.setBackground(new java.awt.Color(255,230,240));
    }//GEN-LAST:event_btnClientsMouseExited

    private void btnReportsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseMoved
        btnReports.setForeground(new java.awt.Color(255,230,240));
        btnReports.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnReportsMouseMoved

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        btnReports.setForeground(new java.awt.Color(0, 0, 0));
        btnReports.setBackground(new java.awt.Color(255,230,240));
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnSettingsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseMoved
        btnSettings.setForeground(new java.awt.Color(255,230,240));
        btnSettings.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnSettingsMouseMoved

    private void btnSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseExited
        btnSettings.setForeground(new java.awt.Color(0, 0, 0));
        btnSettings.setBackground(new java.awt.Color(255,230,240));
    }//GEN-LAST:event_btnSettingsMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClients;
    public javax.swing.JButton btnEnterprise;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnProducts;
    public javax.swing.JButton btnReports;
    public javax.swing.JButton btnSeeNotification;
    public javax.swing.JButton btnSeeProfile;
    public javax.swing.JButton btnSettings;
    public javax.swing.JButton btnSignOff;
    public javax.swing.JLabel lblCaelestiDevelopment;
    public javax.swing.JLabel lblLogoOrquidea;
    private javax.swing.JPanel panLateralMenu;
    public javax.swing.JPanel panMain;
    private javax.swing.JPanel panMainMenu;
    public javax.swing.JPanel panMainPanel;
    private javax.swing.JPanel panTopBar;
    // End of variables declaration//GEN-END:variables
}
