
package views;

import lib.SupportFunctions;

/**
 *
 * @author Gustavo
 */
public class MainMenu extends javax.swing.JFrame {

    private int xx = 0, xy = 0;
    
    private SupportFunctions support;
    
    public MainMenu() {
        
        initComponents();
                
        support = new SupportFunctions();
        
        support.initialOps(this);
        
    }

    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor 
     * profundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addActionEvents(java.awt.event.ActionListener evt){
        
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        btnSeeNotification.addActionListener(evt);
        btnSeeProfile.addActionListener(evt);
        btnSignOff.addActionListener(evt);
        
        btnChangePhoto.addActionListener(evt);
        btnDeletePhoto.addActionListener(evt);
        
    }
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * objeto) añadiendo este evento a una lista que será manejada con mayor 
     * profundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta MouseListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por acciones en 
     * cietos tipos de objetos.
     * @param evt 
     */
    public void addMouseEvents(java.awt.event.MouseListener evt){
        
        
        
    }
    
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMainMenu = new javax.swing.JPanel();
        panTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSignOff = new javax.swing.JButton();
        btnSeeProfile = new javax.swing.JButton();
        btnSeeNotification = new javax.swing.JButton();
        panMainPanel = new javax.swing.JPanel();
        panProfile = new javax.swing.JPanel();
        lblProfilePhotoUser = new javax.swing.JLabel();
        btnDeletePhoto = new javax.swing.JButton();
        btnChangePhoto = new javax.swing.JButton();
        panLateralMenu = new javax.swing.JPanel();
        lblCaelestiDevelopment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 249, 249));
        setUndecorated(true);
        setResizable(false);

        panMainMenu.setBackground(new java.awt.Color(255, 245, 249));
        panMainMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 144, 158)));

        panTopBar.setBackground(new java.awt.Color(255, 245, 249));
        panTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panTopBarMouseDragged(evt);
            }
        });
        panTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(255, 245, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/minIcon32.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 245, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/closeIcon32.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        btnSignOff.setBackground(new java.awt.Color(255, 245, 249));
        btnSignOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/signOffIcon32.png"))); // NOI18N
        btnSignOff.setToolTipText("Cerrar Sesión");
        btnSignOff.setBorder(null);
        btnSignOff.setBorderPainted(false);
        btnSignOff.setContentAreaFilled(false);
        btnSignOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignOff.setFocusPainted(false);
        btnSignOff.setOpaque(true);
        btnSignOff.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSignOffMouseMoved(evt);
            }
        });
        btnSignOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignOffMouseExited(evt);
            }
        });

        btnSeeProfile.setBackground(new java.awt.Color(255, 245, 249));
        btnSeeProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/accountProfileIcon32.png"))); // NOI18N
        btnSeeProfile.setToolTipText("Ver Perfil");
        btnSeeProfile.setBorder(null);
        btnSeeProfile.setBorderPainted(false);
        btnSeeProfile.setContentAreaFilled(false);
        btnSeeProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeeProfile.setFocusPainted(false);
        btnSeeProfile.setOpaque(true);
        btnSeeProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeeProfileMouseMoved(evt);
            }
        });
        btnSeeProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeeProfileMouseExited(evt);
            }
        });

        btnSeeNotification.setBackground(new java.awt.Color(255, 245, 249));
        btnSeeNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/medium/notificationOffIcon32.png"))); // NOI18N
        btnSeeNotification.setToolTipText("Ver notificaciones");
        btnSeeNotification.setBorder(null);
        btnSeeNotification.setBorderPainted(false);
        btnSeeNotification.setContentAreaFilled(false);
        btnSeeNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeeNotification.setFocusPainted(false);
        btnSeeNotification.setOpaque(true);
        btnSeeNotification.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeeNotificationMouseMoved(evt);
            }
        });
        btnSeeNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeeNotificationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panTopBarLayout = new javax.swing.GroupLayout(panTopBar);
        panTopBar.setLayout(panTopBarLayout);
        panTopBarLayout.setHorizontalGroup(
            panTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopBarLayout.createSequentialGroup()
                .addContainerGap(516, Short.MAX_VALUE)
                .addComponent(btnSeeNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeeProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(14, 14, 14))
        );
        panTopBarLayout.setVerticalGroup(
            panTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSignOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSeeProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSeeNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panMainPanel.setBackground(new java.awt.Color(255, 245, 249));
        panMainPanel.setLayout(new java.awt.CardLayout());

        panProfile.setBackground(new java.awt.Color(255, 245, 249));

        lblProfilePhotoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePhotoUser.setText("Sin imagen");
        lblProfilePhotoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 144, 158)));

        btnDeletePhoto.setBackground(new java.awt.Color(254, 220, 234));
        btnDeletePhoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeletePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletePhoto.setText("Eliminar");
        btnDeletePhoto.setToolTipText("Eliminar foto");
        btnDeletePhoto.setBorder(null);
        btnDeletePhoto.setBorderPainted(false);
        btnDeletePhoto.setContentAreaFilled(false);
        btnDeletePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePhoto.setFocusPainted(false);
        btnDeletePhoto.setOpaque(true);
        btnDeletePhoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeletePhotoMouseMoved(evt);
            }
        });
        btnDeletePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletePhotoMouseExited(evt);
            }
        });

        btnChangePhoto.setBackground(new java.awt.Color(254, 220, 234));
        btnChangePhoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePhoto.setText("Cambiar");
        btnChangePhoto.setToolTipText("Cambiar foto");
        btnChangePhoto.setBorder(null);
        btnChangePhoto.setBorderPainted(false);
        btnChangePhoto.setContentAreaFilled(false);
        btnChangePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePhoto.setFocusPainted(false);
        btnChangePhoto.setOpaque(true);
        btnChangePhoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChangePhotoMouseMoved(evt);
            }
        });
        btnChangePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePhotoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panProfileLayout = new javax.swing.GroupLayout(panProfile);
        panProfile.setLayout(panProfileLayout);
        panProfileLayout.setHorizontalGroup(
            panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProfileLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfilePhotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panProfileLayout.createSequentialGroup()
                        .addComponent(btnChangePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        panProfileLayout.setVerticalGroup(
            panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProfileLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblProfilePhotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        panMainPanel.add(panProfile, "card2");

        panLateralMenu.setBackground(new java.awt.Color(255, 230, 240));
        panLateralMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panLateralMenuMouseDragged(evt);
            }
        });
        panLateralMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panLateralMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panLateralMenuMouseReleased(evt);
            }
        });

        lblCaelestiDevelopment.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCaelestiDevelopment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/small/Caelesti Small.png"))); // NOI18N
        lblCaelestiDevelopment.setText("Caelesti Development");

        javax.swing.GroupLayout panLateralMenuLayout = new javax.swing.GroupLayout(panLateralMenu);
        panLateralMenu.setLayout(panLateralMenuLayout);
        panLateralMenuLayout.setHorizontalGroup(
            panLateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCaelestiDevelopment, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        panLateralMenuLayout.setVerticalGroup(
            panLateralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCaelestiDevelopment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panMainMenuLayout = new javax.swing.GroupLayout(panMainMenu);
        panMainMenu.setLayout(panMainMenuLayout);
        panMainMenuLayout.setHorizontalGroup(
            panMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainMenuLayout.createSequentialGroup()
                .addComponent(panLateralMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panMainMenuLayout.setVerticalGroup(
            panMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainMenuLayout.createSequentialGroup()
                .addComponent(panTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
            .addComponent(panLateralMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMainMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnSignOffMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOffMouseMoved
        btnSignOff.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnSignOffMouseMoved

    private void btnSignOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOffMouseExited
        btnSignOff.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnSignOffMouseExited

    private void btnSeeProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeProfileMouseMoved
        btnSeeProfile.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnSeeProfileMouseMoved

    private void btnSeeProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeProfileMouseExited
        btnSeeProfile.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnSeeProfileMouseExited

    private void btnSeeNotificationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeNotificationMouseMoved
        btnSeeNotification.setBackground(new java.awt.Color(254, 220, 234));
    }//GEN-LAST:event_btnSeeNotificationMouseMoved

    private void btnSeeNotificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeeNotificationMouseExited
        btnSeeNotification.setBackground(new java.awt.Color(255,245,249));
    }//GEN-LAST:event_btnSeeNotificationMouseExited

    private void panTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panTopBarMouseDragged

    private void panTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panTopBarMousePressed

    private void panTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panTopBarMouseReleased

    private void panLateralMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLateralMenuMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panLateralMenuMouseDragged

    private void panLateralMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLateralMenuMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panLateralMenuMousePressed

    private void panLateralMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLateralMenuMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panLateralMenuMouseReleased

    private void btnDeletePhotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePhotoMouseMoved
        btnDeletePhoto.setForeground(new java.awt.Color(255,230,240));
        btnDeletePhoto.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnDeletePhotoMouseMoved

    private void btnDeletePhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePhotoMouseExited
        btnDeletePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletePhoto.setBackground(new java.awt.Color(254,220,234));
    }//GEN-LAST:event_btnDeletePhotoMouseExited

    private void btnChangePhotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePhotoMouseMoved
        btnChangePhoto.setForeground(new java.awt.Color(255,230,240));
        btnChangePhoto.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnChangePhotoMouseMoved

    private void btnChangePhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePhotoMouseExited
        btnChangePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePhoto.setBackground(new java.awt.Color(254,220,234));
    }//GEN-LAST:event_btnChangePhotoMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChangePhoto;
    public javax.swing.JButton btnDeletePhoto;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnSeeNotification;
    public javax.swing.JButton btnSeeProfile;
    public javax.swing.JButton btnSignOff;
    public javax.swing.JLabel lblCaelestiDevelopment;
    public javax.swing.JLabel lblProfilePhotoUser;
    private javax.swing.JPanel panLateralMenu;
    private javax.swing.JPanel panMainMenu;
    public javax.swing.JPanel panMainPanel;
    public javax.swing.JPanel panProfile;
    private javax.swing.JPanel panTopBar;
    // End of variables declaration//GEN-END:variables
}
