
package views.mainMenuOptions;

/**
 *
 * @author Gustavo
 */
public class Profile extends javax.swing.JPanel {

    
    public Profile() {
        initComponents();
    }

    public void addEvents(java.awt.event.ActionListener evt) {
        
        btnChangePhoto.addActionListener(evt);
        btnDeletePhoto.addActionListener(evt);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePhotoUser = new javax.swing.JLabel();
        btnDeletePhoto = new javax.swing.JButton();
        btnChangePhoto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 245, 249));

        lblProfilePhotoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePhotoUser.setText("Sin imagen");
        lblProfilePhotoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 144, 158)));

        btnDeletePhoto.setBackground(new java.awt.Color(254, 220, 234));
        btnDeletePhoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeletePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletePhoto.setText("Eliminar");
        btnDeletePhoto.setToolTipText("Eliminar foto");
        btnDeletePhoto.setBorder(null);
        btnDeletePhoto.setBorderPainted(false);
        btnDeletePhoto.setContentAreaFilled(false);
        btnDeletePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePhoto.setFocusPainted(false);
        btnDeletePhoto.setOpaque(true);
        btnDeletePhoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeletePhotoMouseMoved(evt);
            }
        });
        btnDeletePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletePhotoMouseExited(evt);
            }
        });

        btnChangePhoto.setBackground(new java.awt.Color(254, 220, 234));
        btnChangePhoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePhoto.setText("Cambiar");
        btnChangePhoto.setToolTipText("Cambiar foto");
        btnChangePhoto.setBorder(null);
        btnChangePhoto.setBorderPainted(false);
        btnChangePhoto.setContentAreaFilled(false);
        btnChangePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePhoto.setFocusPainted(false);
        btnChangePhoto.setOpaque(true);
        btnChangePhoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChangePhotoMouseMoved(evt);
            }
        });
        btnChangePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePhotoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfilePhotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblProfilePhotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePhotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePhotoMouseMoved
        btnChangePhoto.setForeground(new java.awt.Color(255,230,240));
        btnChangePhoto.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnChangePhotoMouseMoved

    private void btnChangePhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePhotoMouseExited
        btnChangePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePhoto.setBackground(new java.awt.Color(254,220,234));
    }//GEN-LAST:event_btnChangePhotoMouseExited

    private void btnDeletePhotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePhotoMouseMoved
        btnDeletePhoto.setForeground(new java.awt.Color(255,230,240));
        btnDeletePhoto.setBackground(new java.awt.Color(194, 48, 111));
    }//GEN-LAST:event_btnDeletePhotoMouseMoved

    private void btnDeletePhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePhotoMouseExited
        btnDeletePhoto.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletePhoto.setBackground(new java.awt.Color(254,220,234));
    }//GEN-LAST:event_btnDeletePhotoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChangePhoto;
    public javax.swing.JButton btnDeletePhoto;
    public javax.swing.JLabel lblProfilePhotoUser;
    // End of variables declaration//GEN-END:variables
}
